# -*- coding: utf-8 -*-
"""B1_CyberGlove_static_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vmD_FHcLsBFeojpHOGt73X6OHfiDfNb

# Comparació estàtica CyberGlove vs mà robòtica

Aquest notebook compara les posicions estàtiques del guant amb les posicions deterministes de la mà robòtica.

## Entrada esperada

Fitxers del guant:

```text
A_BotiStat1.yaml, A_BotiStat2.yaml, A_BotiStat3.yaml
A_OneStat1.yaml, A_OneStat2.yaml, A_OneStat3.yaml
A_PaperStat1.yaml, A_PaperStat2.yaml, A_PaperStat3.yaml
A_RockStat1.yaml, A_RockStat2.yaml, A_RockStat3.yaml
A_ScisStat1.yaml, A_ScisStat2.yaml, A_ScisStat3.yaml
A_ThumbUpStat1.yaml, A_ThumbUpStat2.yaml, A_ThumbUpStat3.yaml
```

També funciona si només tens 1 o 2 versions.

Fitxer de rangs del guant:

```text
AA_Rangs1.yaml
```

## Sortida

Es generen plots en escala **0–100**:

- guant normalitzat amb els rangs del guant;
- robot normalitzat amb els seus `q_min` i `q_max`;
- plots temporals per dit;
- resum per posició;
- barplot guant mitjà ;
- CSV de mètriques;
- heatmap global de diferències.


Aquesta versió inclou tots els grups del guant: canell, polze, índex, mig, anular i menovell. No fa cap comparació amb el robot.
"""

import yaml
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ============================================================
# CONFIGURACIÓ GENERAL
# ============================================================

data_dir = Path(".")
ranges_yaml_path = Path("AA_Rangs1.yaml")

glove_value_key = "calib_deg"

clip_glove_to_0_100 = True
clip_robot_to_0_100 = True

save_figures = True
save_pdf = True
output_dir = Path("plots_static_glove_vs_robot_0_100")
output_dir.mkdir(exist_ok=True)

screen_dpi = 170
export_dpi = 300
smoothing_window = 1

plt.rcParams.update({
    "figure.dpi": screen_dpi,
    "savefig.dpi": export_dpi,
    "font.size": 11,
    "axes.titlesize": 15,
    "axes.labelsize": 12,
    "legend.fontsize": 8,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "lines.linewidth": 2.0,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linestyle": "--",
    "axes.spines.top": False,
    "axes.spines.right": False,
})

# ============================================================
# ORDRE REAL DELS FITXERS DEL GUANT
# ============================================================

glove_sensor_order = [
    "Wrist j1", "Wrist j0",
    "Index j1", "Index j2", "Index j3", "Index j0",
    "Middle j1", "Middle j2", "Middle j3", "Middle j0",
    "Annular j1", "Annular j2", "Annular j3", "Annular j0",
    "Pinky j1", "Pinky j2", "Pinky j3", "Pinky j0",
    "Thumb j1", "Thumb j2", "Thumb j3", "Thumb j0",
]

finger_groups = {
    "Wrist": ["Wrist j1", "Wrist j0"],
    "Thumb": ["Thumb j1", "Thumb j2", "Thumb j3", "Thumb j0"],
    "Index": ["Index j1", "Index j2", "Index j3", "Index j0"],
    "Middle": ["Middle j1", "Middle j2", "Middle j3", "Middle j0"],
    "Annular": ["Annular j1", "Annular j2", "Annular j3", "Annular j0"],
    "Pinky": ["Pinky j1", "Pinky j2", "Pinky j3", "Pinky j0"],
}

glove_plot_joints = [joint for joints in finger_groups.values() for joint in joints]
comparison_joints = glove_plot_joints

static_positions = {
    "botifarra": {"label": "Botifarra", "prefix": "A_BotiStat"},
    "one": {"label": "One", "prefix": "A_OneStat"},
    "paper": {"label": "Paper", "prefix": "A_PaperStat"},
    "rock": {"label": "Rock", "prefix": "A_RockStat"},
    "scissors": {"label": "Scissors", "prefix": "A_ScisStat"},
    "thumb_up": {"label": "Thumb Up", "prefix": "A_ThumbUpStat"},
}


# ============================================================
# COLORS FIXOS PER TIPUS DE JOINT
# ============================================================
# Mateix color per al mateix tipus de joint independentment del dit:
# j0 = blau, j1 = vermell, j2 = verd, j3 = taronja.
# El canell té dos colors propis.

joint_type_color_map = {
    "j0": "#1f77b4",   # blau
    "j1": "#d62728",   # vermell
    "j2": "#2ca02c",   # verd
    "j3": "#ff7f0e",   # taronja
}

wrist_color_map = {
    "Wrist j0": "#9467bd",  # lila
    "Wrist j1": "#8c564b",  # marró
}

def get_joint_color(joint):
    if joint in wrist_color_map:
        return wrist_color_map[joint]

    joint_type = joint.split()[-1]

    return joint_type_color_map.get(
        joint_type,
        None,
    )

# Es manté aquest nom perquè la resta del codi no s'hagi de tocar.
joint_color_map = {
    joint: get_joint_color(joint)
    for joint in glove_plot_joints
}

version_line_styles = {
    1: "-",
    2: "--",
    3: "-.",
    4: ":",
    5: (0, (3, 1, 1, 1)),
}

recording_line_styles = [
    "-",
    "--",
    "-.",
    ":",
    (0, (3, 1, 1, 1)),
]

# ============================================================
# FUNCIONS
# ============================================================

def get_range_keys(value_key):
    if value_key == "calib_deg":
        return "calib_min_deg", "calib_max_deg"
    if value_key == "raw_deg":
        return "raw_min_deg", "raw_max_deg"
    if value_key == "calib_rad":
        return "calib_min_rad", "calib_max_rad"
    if value_key == "raw_rad":
        return "raw_min_rad", "raw_max_rad"
    raise ValueError(f"value_key no reconegut: {value_key}")


def load_glove_ranges_by_joint_name(path, value_key):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    min_key, max_key = get_range_keys(value_key)
    ranges = {}

    for sensor in data["sensor_range"]["sensors"]:
        ranges[sensor["name"]] = {
            "min": sensor[min_key],
            "max": sensor[max_key],
        }

    return ranges


def normalize_to_0_100(values, vmin, vmax, clip=True):
    values = np.asarray(values, dtype=float)
    if vmax == vmin:
        return np.zeros_like(values)

    out = (values - vmin) / (vmax - vmin) * 100

    if clip:
        out = np.clip(out, 0, 100)

    return out


def load_static_glove_yaml(path, value_key):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    recording = data["recording"]
    samples = recording["samples"]
    sensor_names = recording.get("sensor_names", glove_sensor_order)

    rows = []

    for sample in samples:
        values = sample[value_key]
        row = {"t": sample["t"]}

        if len(values) != len(sensor_names):
            raise ValueError(
                f"{path.name}: {len(values)} valors però {len(sensor_names)} sensor_names."
            )

        for name, value in zip(sensor_names, values):
            row[name] = value

        rows.append(row)

    return pd.DataFrame(rows), recording


def normalize_glove_df(df_raw, glove_ranges):
    df = pd.DataFrame()
    df["t"] = df_raw["t"]

    for joint in comparison_joints:
        r = glove_ranges[joint]
        df[joint] = normalize_to_0_100(
            df_raw[joint],
            r["min"],
            r["max"],
            clip=clip_glove_to_0_100,
        )

    return df


def find_static_files(prefix):
    files = []
    for ext in ["yaml", "yml"]:
        files.extend(data_dir.glob(f"{prefix}*.{ext}"))

    def get_num(path):
        m = re.search(r"(\d+)\.ya?ml$", path.name)
        return int(m.group(1)) if m else 999

    return sorted(files, key=get_num)


def smooth_series(series, window):
    if window <= 1:
        return series
    return series.rolling(window=window, center=True, min_periods=1).mean()


def nice_filename(text):
    rep = {
        "í": "i", "Í": "I", "à": "a", "À": "A",
        "è": "e", "È": "E", "é": "e", "É": "E",
        "ó": "o", "Ó": "O", "ò": "o", "Ò": "O",
        "ú": "u", "Ú": "U", "ç": "c", "Ç": "C",
        " ": "_", "/": "_",
    }
    for a, b in rep.items():
        text = text.replace(a, b)
    return text.lower()


def save_figure(fig, folder, filename):
    folder.mkdir(parents=True, exist_ok=True)
    fig.savefig(folder / f"{filename}.png", bbox_inches="tight")
    if save_pdf:
        fig.savefig(folder / f"{filename}.pdf", bbox_inches="tight")

# ============================================================
# CARREGAR GUANT I CALCULAR ESTADÍSTIQUES
# ============================================================

glove_ranges = load_glove_ranges_by_joint_name(
    ranges_yaml_path,
    glove_value_key,
)

glove_static_data = {}
glove_stats = {}

for position_key, info in static_positions.items():
    files = find_static_files(info["prefix"])

    print(f"{info['label']}: {len(files)} fitxers trobats")

    recordings = []

    for path in files:
        df_raw, recording = load_static_glove_yaml(path, glove_value_key)
        df_norm = normalize_glove_df(df_raw, glove_ranges)

        recordings.append({
            "path": path,
            "label": path.stem,
            "df_raw": df_raw,
            "df_norm": df_norm,
            "recording": recording,
        })

    glove_static_data[position_key] = {
        "info": info,
        "files": files,
        "recordings": recordings,
    }

    if not recordings:
        continue

    rows = []
    for rec in recordings:
        row = {"recording": rec["label"]}
        df = rec["df_norm"]

        for joint in glove_plot_joints:
            row[f"{joint}_mean"] = df[joint].mean()
            row[f"{joint}_std"] = df[joint].std()

        rows.append(row)

    rec_df = pd.DataFrame(rows)

    summary_rows = []
    for joint in glove_plot_joints:
        means = rec_df[f"{joint}_mean"].to_numpy(dtype=float)
        summary_rows.append({
            "joint": joint,
            "glove_mean_percent": np.nanmean(means),
            "glove_std_between_recordings_percent": np.nanstd(means),
            "glove_min_recording_mean_percent": np.nanmin(means),
            "glove_max_recording_mean_percent": np.nanmax(means),
        })

    summary_df = pd.DataFrame(summary_rows)

    glove_stats[position_key] = {
        "recordings_df": rec_df,
        "summary_df": summary_df,
    }

    folder = output_dir / position_key
    folder.mkdir(parents=True, exist_ok=True)

    rec_df.to_csv(folder / f"{position_key}_glove_recordings_stats.csv", index=False)
    summary_df.to_csv(folder / f"{position_key}_glove_summary_stats.csv", index=False)

# ============================================================
# PLOTS TEMPORALS PER DIT
# ============================================================

def plot_static_time_finger(position_key, group_name, joints):
    data = glove_static_data[position_key]
    info = data["info"]
    recordings = data["recordings"]

    if not recordings:
        return

    fig, ax = plt.subplots(figsize=(12, 5.8), dpi=screen_dpi)

    for rec_idx, rec in enumerate(recordings):
        df = rec["df_norm"]
        linestyle = recording_line_styles[rec_idx % len(recording_line_styles)]

        for joint in joints:
            ax.plot(
                df["t"],
                smooth_series(df[joint], smoothing_window),
                label=f"{rec['label']} · {joint}",
                color=joint_color_map.get(joint, None),
                linestyle=linestyle,
                alpha=0.88,
            )

    ax.set_title(
        f"{group_name} — {info['label']} — glove",
        pad=14,
        fontweight="bold",
    )
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Joint movement (%)")
    ax.set_ylim(-5, 105)

    ax.legend(
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        frameon=True,
        title="Trial · Joint",
    )

    fig.tight_layout()

    if save_figures:
        folder = output_dir / position_key
        filename = f"{position_key}_{nice_filename(group_name)}_temps_0_100_guant"
        save_figure(fig, folder, filename)

    plt.show()


for position_key, data in glove_static_data.items():
    if not data["recordings"]:
        continue

    for group_name, joints in finger_groups.items():
        plot_static_time_finger(position_key, group_name, joints)

# ============================================================
# FIGURA RESUM PER POSICIÓ
# ============================================================

def plot_static_summary(position_key):
    data = glove_static_data[position_key]
    info = data["info"]
    recordings = data["recordings"]

    if not recordings:
        return

    n_rows = 3
    n_cols = 2

    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(24, 14),
        dpi=screen_dpi,
        sharex=True,
        constrained_layout=True,
    )

    axes = axes.flatten()

    for ax, (group_name, joints) in zip(axes, finger_groups.items()):
        for rec_idx, rec in enumerate(recordings):
            df = rec["df_norm"]
            linestyle = recording_line_styles[rec_idx % len(recording_line_styles)]

            for joint in joints:
                ax.plot(
                    df["t"],
                    smooth_series(df[joint], smoothing_window),
                    label=f"{rec['label']} · {joint}",
                    color=joint_color_map.get(joint, None),
                    linestyle=linestyle,
                    alpha=0.88,
                )

        ax.set_title(group_name, fontweight="bold")
        ax.set_ylabel("Movement (%)")
        ax.set_ylim(-5, 105)

        ax.legend(
            fontsize=6.5,
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            frameon=True,
            title="Trial · Joint",
            title_fontsize=7,
        )

    # Etiqueta de temps només a l'última fila
    for ax in axes[-n_cols:]:
        ax.set_xlabel("Time (s)")

    fig.suptitle(
        f"{info['label']} — Glove's static summary",
        fontsize=18,
        fontweight="bold",
    )

    if save_figures:
        folder = output_dir / position_key
        filename = f"{position_key}_resum_temps_0_100_guant_3x2"
        save_figure(fig, folder, filename)

    plt.show()


for position_key in static_positions:
    plot_static_summary(position_key)

# ============================================================
# TAULES I BARPLOTS DEL GUANT
# ============================================================

def build_glove_summary_table(position_key):
    if position_key not in glove_stats:
        return None

    info = glove_static_data[position_key]["info"]
    summary = glove_stats[position_key]["summary_df"].set_index("joint")

    rows = []

    for joint in glove_plot_joints:
        glove_mean = summary.loc[joint, "glove_mean_percent"]
        glove_std = summary.loc[joint, "glove_std_between_recordings_percent"]
        glove_min = summary.loc[joint, "glove_min_recording_mean_percent"]
        glove_max = summary.loc[joint, "glove_max_recording_mean_percent"]

        rows.append({
            "position": position_key,
            "label": info["label"],
            "joint": joint,
            "glove_mean_percent": glove_mean,
            "glove_std_between_recordings_percent": glove_std,
            "glove_min_recording_mean_percent": glove_min,
            "glove_max_recording_mean_percent": glove_max,
        })

    return pd.DataFrame(rows)


all_glove_summaries = []

for position_key in static_positions:
    table = build_glove_summary_table(position_key)

    if table is None:
        continue

    all_glove_summaries.append(table)

    folder = output_dir / position_key
    table.to_csv(folder / f"{position_key}_summary_glove_0_100.csv", index=False)

    x = np.arange(len(table))

    fig, ax = plt.subplots(figsize=(14, 6), dpi=screen_dpi)

    bar_colors = [
        joint_color_map.get(joint, None)
        for joint in table["joint"]
    ]

    ax.bar(
        x,
        table["glove_mean_percent"],
        yerr=table["glove_std_between_recordings_percent"],
        capsize=4,
        label="Glove's mean ± std between trials",
        color=bar_colors,
    )

    ax.set_title(
        f"{table['label'].iloc[0]} — Glove's mean summary",
        pad=14,
        fontweight="bold",
    )
    ax.set_xlabel("Joint")
    ax.set_ylabel("Joint movement (%)")
    ax.set_ylim(-5, 105)
    ax.set_xticks(x)
    ax.set_xticklabels(table["joint"], rotation=45, ha="right")

    ax.legend(
        frameon=True,
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
    )

    fig.tight_layout()

    if save_figures:
        filename = f"{position_key}_barplot_guant_mitja_0_100"
        save_figure(fig, folder, filename)

    plt.show()


if all_glove_summaries:
    glove_summary_df = pd.concat(all_glove_summaries, ignore_index=True)
    glove_summary_df.to_csv(
        output_dir / "all_static_positions_summary_glove_0_100.csv",
        index=False,
    )
    display(glove_summary_df.sort_values(["position", "joint"]))

"""## Nota sobre el mapping del robot

El codi assumeix que els 4 valors de cada dit del robot corresponen a:

```text
j1, j2, j3, j0
```

Això es fa per comparar directament amb els noms del guant:

```text
Index j1, Index j2, Index j3, Index j0
```

Si el teu vector del robot està realment en ordre:

```text
j0, j1, j2, j3
```

canvia només la variable:

```python
robot_joint_order_for_comparison
```

La resta del codi no cal tocar-la.

"""



# ============================================================
# DESCARREGAR RESULTATS DE COLAB EN ZIP
# ============================================================

import shutil
from pathlib import Path

zip_name = "resultats_estatic"

zip_path = shutil.make_archive(
    zip_name,
    "zip",
    output_dir,
)

print("ZIP creat:", zip_path)

try:
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print("No s'ha pogut iniciar la descàrrega automàtica.")
    print("Pots descarregar manualment aquest fitxer:")
    print(zip_path)
    print("Error:", e)