# -*- coding: utf-8 -*-
"""B2_CyberGlove_movements_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iuZ7UK74TbwJHnrKW16dxawODAYZZeW0

# CyberGlove — multi-moviments normalitzats 0–100 per nom de joint

Aquest notebook carrega automàticament tots els moviments:

```text
A_Mov_*.yaml
```

i normalitza cada joint utilitzant el fitxer:

```text
AA_Anna_Rangs.yaml
```

Punt clau:

> La normalització es fa **per nom de joint**, no per posició.

És a dir:

```text
df["Index j1"]  → busca "Index j1" a AA_Rangs1.yaml
df["Thumb j2"]  → busca "Thumb j2" a AA_Rangs1.yaml
df["Wrist j1"]  → busca "Wrist j1" a AA_Rangs1.yaml
```

Per tant, encara que l’ordre dels joints sigui diferent entre el fitxer de moviment i el fitxer de rangs, la normalització és correcta.

L’eix X és el temps real en segons.  
L’eix Y és el percentatge del rang de moviment del joint, de 0 a 100.
"""

import yaml
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

# ============================================================
# CONFIGURACIÓ GENERAL
# ============================================================

data_dir = Path(".")
file_pattern = "A_Mov_*.yaml"
ranges_yaml_path = Path("AA_Rangs1.yaml")

# raw_deg, raw_rad, calib_deg, calib_rad
value_key = "calib_deg"

# Recomanat per visualització
clip_to_0_100 = True

save_figures = True
save_pdf = True
output_dir = Path("plots_moviments_normalitzats_0_100")
output_dir.mkdir(exist_ok=True)

screen_dpi = 170
export_dpi = 300

# 1 = sense suavitzar
smoothing_window = 1

plt.rcParams.update({
    "figure.dpi": screen_dpi,
    "savefig.dpi": export_dpi,
    "font.size": 11,
    "axes.titlesize": 15,
    "axes.labelsize": 12,
    "legend.fontsize": 8,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "lines.linewidth": 2.0,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linestyle": "-",
    "axes.spines.top": False,
    "axes.spines.right": False,
})

# ============================================================
# ORDRE REAL DELS FITXERS DE MOVIMENT
# ============================================================

movement_sensor_order = [
    "Wrist j1",
    "Wrist j0",

    "Index j1",
    "Index j2",
    "Index j3",
    "Index j0",

    "Middle j1",
    "Middle j2",
    "Middle j3",
    "Middle j0",

    "Annular j1",
    "Annular j2",
    "Annular j3",
    "Annular j0",

    "Pinky j1",
    "Pinky j2",
    "Pinky j3",
    "Pinky j0",

    "Thumb j1",
    "Thumb j2",
    "Thumb j3",
    "Thumb j0",
]

pd.DataFrame({
    "index": range(len(movement_sensor_order)),
    "joint": movement_sensor_order,
})

# ============================================================
# AGRUPACIÓ VISUAL PER DITS
# ============================================================

sensor_groups = {
    "Wrist": [
        "Wrist j1",
        "Wrist j0",
    ],

    "Thumb": [
        "Thumb j1",
        "Thumb j2",
        "Thumb j3",
        "Thumb j0",
    ],

    "Index": [
        "Index j1",
        "Index j2",
        "Index j3",
        "Index j0",
    ],

    "Middle": [
        "Middle j1",
        "Middle j2",
        "Middle j3",
        "Middle j0",
    ],

    "Annular": [
        "Annular j1",
        "Annular j2",
        "Annular j3",
        "Annular j0",
    ],

    "Pinky": [
        "Pinky j1",
        "Pinky j2",
        "Pinky j3",
        "Pinky j0",
    ],
}

all_joints = [
    joint
    for joints in sensor_groups.values()
    for joint in joints
]


# ============================================================
# COLORS FIXOS PER TIPUS DE JOINT
# ============================================================
# Mateix color per al mateix tipus de joint independentment del dit:
# j0 = blau, j1 = vermell, j2 = verd, j3 = taronja.
# El canell té dos colors propis.

joint_type_color_map = {
    "j0": "#1f77b4",   # blau
    "j1": "#d62728",   # vermell
    "j2": "#2ca02c",   # verd
    "j3": "#ff7f0e",   # taronja
}

wrist_color_map = {
    "Wrist j0": "#9467bd",  # lila
    "Wrist j1": "#8c564b",  # marró
}

def get_joint_color(joint):
    if joint in wrist_color_map:
        return wrist_color_map[joint]

    joint_type = joint.split()[-1]

    return joint_type_color_map.get(
        joint_type,
        None,
    )

# Es manté aquest nom perquè la resta del codi no s'hagi de tocar.
joint_color_map = {
    joint: get_joint_color(joint)
    for joint in all_joints
}

version_line_styles = {
    1: "-",
    2: "--",
    3: "-.",
    4: ":",
    5: (0, (3, 1, 1, 1)),
}

recording_line_styles = [
    "-",
    "--",
    "-.",
    ":",
    (0, (3, 1, 1, 1)),
]

movement_names = {
    "PB": "Paper → Botifarra",
    "PO": "Paper → One",
    "PR": "Paper → Rock",
    "PS": "Paper → Scissors",
    "PT": "Paper → Thumb Up",

    "RB": "Rock → Botifarra",
    "RO": "Rock → One",
    "RP": "Rock → Paper",
    "RS": "Rock → Scissors",
    "RT": "Rock → Thumb Up",
}

# ============================================================
# FUNCIONS DE CÀRREGA
# ============================================================

def parse_movement_file(path):
    match = re.match(
        r"A_Mov_([A-Z]{2})(\d+)\.ya?ml$",
        path.name,
    )

    if not match:
        return None

    movement_code = match.group(1)
    version = int(match.group(2))

    return {
        "movement_code": movement_code,
        "version": version,
        "path": path,
        "file": path.name,
        "movement_name": movement_names.get(movement_code, movement_code),
    }


def find_movement_files(data_dir, file_pattern):
    rows = []

    for path in sorted(data_dir.glob(file_pattern)):
        parsed = parse_movement_file(path)

        if parsed is not None:
            rows.append(parsed)

    return pd.DataFrame(rows)


def get_range_keys(value_key):
    if value_key == "calib_deg":
        return "calib_min_deg", "calib_max_deg"
    if value_key == "raw_deg":
        return "raw_min_deg", "raw_max_deg"
    if value_key == "calib_rad":
        return "calib_min_rad", "calib_max_rad"
    if value_key == "raw_rad":
        return "raw_min_rad", "raw_max_rad"

    raise ValueError(f"value_key no reconegut: {value_key}")


def load_ranges_by_joint_name(ranges_yaml_path, value_key="calib_deg"):
    """Carrega els rangs fent servir el nom del joint com a clau.

    Exemple:
    ranges["Index j1"] = {"min": ..., "max": ...}

    Això evita errors si el fitxer de rangs i el fitxer de moviments tenen ordres diferents.
    """

    with open(ranges_yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    min_key, max_key = get_range_keys(value_key)

    sensors = data["sensor_range"]["sensors"]

    ranges = {}

    for sensor in sensors:
        joint_name = sensor["name"]

        ranges[joint_name] = {
            "min": sensor[min_key],
            "max": sensor[max_key],
        }

    return ranges


def load_movement_using_yaml_sensor_names(movement_yaml_path, value_key="calib_deg"):
    """Carrega el moviment respectant l'ordre sensor_names del mateix YAML.

    Si el YAML porta sensor_names, s'utilitza aquell ordre.
    Si no el porta, s'utilitza movement_sensor_order com a ordre esperat.
    """

    with open(movement_yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    recording = data["recording"]
    samples = recording["samples"]

    sensor_names = recording.get("sensor_names", movement_sensor_order)

    rows = []

    for sample in samples:
        values = sample[value_key]

        if len(values) != len(sensor_names):
            raise ValueError(
                f"El fitxer {movement_yaml_path.name} té {len(values)} valors, "
                f"però sensor_names en defineix {len(sensor_names)}."
            )

        row = {
            "t": sample["t"],
        }

        for joint_name, value in zip(sensor_names, values):
            row[joint_name] = value

        rows.append(row)

    df = pd.DataFrame(rows)

    return df, recording, sensor_names

# ============================================================
# NORMALITZACIÓ 0-100 PER NOM DE JOINT
# ============================================================

def normalize_to_0_100_by_joint_name(df, ranges_by_joint_name, joints, clip=True):
    """Normalitza cada columna del moviment utilitzant el rang del mateix nom.

    Exemple:
    columna df["Index j1"] es normalitza amb ranges_by_joint_name["Index j1"].
    """

    norm_df = pd.DataFrame()
    norm_df["t"] = df["t"]

    constant_joints = []
    missing_range_joints = []
    missing_data_joints = []

    for joint in joints:
        if joint not in df.columns:
            norm_df[joint] = np.nan
            missing_data_joints.append(joint)
            continue

        if joint not in ranges_by_joint_name:
            norm_df[joint] = np.nan
            missing_range_joints.append(joint)
            continue

        joint_min = ranges_by_joint_name[joint]["min"]
        joint_max = ranges_by_joint_name[joint]["max"]

        denominator = joint_max - joint_min

        if denominator == 0:
            norm_df[joint] = 0
            constant_joints.append(joint)
        else:
            norm_df[joint] = (df[joint] - joint_min) / denominator * 100

            if clip:
                norm_df[joint] = norm_df[joint].clip(0, 100)

    report = {
        "constant_joints": constant_joints,
        "missing_range_joints": missing_range_joints,
        "missing_data_joints": missing_data_joints,
    }

    return norm_df, report


def smooth_series(series, window=1):
    if window <= 1:
        return series

    return series.rolling(
        window=window,
        center=True,
        min_periods=1,
    ).mean()


def nice_filename(text):
    replacements = {
        "í": "i",
        "Í": "I",
        "à": "a",
        "À": "A",
        "è": "e",
        "È": "E",
        "é": "e",
        "É": "E",
        "ó": "o",
        "Ó": "O",
        "ò": "o",
        "Ò": "O",
        "ú": "u",
        "Ú": "U",
        "ç": "c",
        "Ç": "C",
        "→": "to",
        " ": "_",
        "/": "_",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.lower()


def save_figure(fig, folder, filename):
    folder.mkdir(parents=True, exist_ok=True)

    fig.savefig(
        folder / f"{filename}.png",
        bbox_inches="tight",
    )

    if save_pdf:
        fig.savefig(
            folder / f"{filename}.pdf",
            bbox_inches="tight",
        )

# ============================================================
# DETECCIÓ DE FITXERS I RANGS
# ============================================================

available_files = find_movement_files(
    data_dir,
    file_pattern,
)

ranges_by_joint_name = load_ranges_by_joint_name(
    ranges_yaml_path,
    value_key=value_key,
)

print("Fitxers de moviment trobats:")
display(available_files)

print("Rangs carregats per nom de joint:")
display(
    pd.DataFrame([
        {
            "joint": joint,
            "min": values["min"],
            "max": values["max"],
            "range": values["max"] - values["min"],
        }
        for joint, values in ranges_by_joint_name.items()
    ]).sort_values("joint")
)

# ============================================================
# CARREGAR LES VERSIONS D'UN MOVIMENT
# ============================================================

def load_versions_for_movement(available_files, movement_code):
    movement_rows = available_files[
        available_files["movement_code"] == movement_code
    ].copy()

    if movement_rows.empty:
        return {}, {}

    loaded = {}
    reports = {}

    for _, row in movement_rows.sort_values("version").iterrows():
        df_raw, recording, sensor_names = load_movement_using_yaml_sensor_names(
            row["path"],
            value_key=value_key,
        )

        df_norm, report = normalize_to_0_100_by_joint_name(
            df_raw,
            ranges_by_joint_name,
            all_joints,
            clip=clip_to_0_100,
        )

        label = f"{movement_code}{row['version']}"

        loaded[row["version"]] = {
            "label": label,
            "df_raw": df_raw,
            "df_norm": df_norm,
            "recording": recording,
            "sensor_names": sensor_names,
            "path": row["path"],
            "movement_code": movement_code,
            "movement_name": row["movement_name"],
            "version": row["version"],
        }

        reports[label] = report

    return loaded, reports

# ============================================================
# PLOTS
# ============================================================

def get_max_time(versions_data):
    return max(
        item["df_norm"]["t"].max()
        for item in versions_data.values()
    )


def plot_group_versions_0_100(versions_data, group_name, joints, movement_folder):
    movement_name = next(iter(versions_data.values()))["movement_name"]
    movement_code = next(iter(versions_data.values()))["movement_code"]

    fig, ax = plt.subplots(
        figsize=(12, 5.8),
        dpi=screen_dpi,
    )

    for version, item in versions_data.items():
        df = item["df_norm"]
        linestyle = version_line_styles.get(version, "-")

        for joint in joints:
            signal = smooth_series(
                df[joint],
                smoothing_window,
            )

            ax.plot(
                df["t"],
                signal,
                label=f"{item['label']} · {joint}",
                color=joint_color_map.get(joint, None),
                linestyle=linestyle,
            )

    ax.set_xlim(0, get_max_time(versions_data))
    ax.set_ylim(-5, 105)

    ax.set_title(
        f"{group_name} — {movement_name}",
        pad=14,
        fontweight="bold",
    )

    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Joint movement (%)")

    ax.legend(
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        frameon=True,
        title="Trial · Joint",
    )

    fig.tight_layout()

    if save_figures:
        filename = f"{movement_code}_{nice_filename(group_name)}_temps_real_0_100"
        save_figure(fig, movement_folder, filename)

    plt.show()


def plot_summary_versions_0_100(versions_data, sensor_groups, movement_folder):
    movement_name = next(iter(versions_data.values()))["movement_name"]
    movement_code = next(iter(versions_data.values()))["movement_code"]

    fig, axes = plt.subplots(
        3,
        2,
        figsize=(24, 13),
        dpi=screen_dpi,
        sharex=True,
        constrained_layout=True,
    )

    axes = axes.flatten()
    max_time = get_max_time(versions_data)

    for ax, (group_name, joints) in zip(
        axes,
        sensor_groups.items(),
    ):
        for version, item in versions_data.items():
            df = item["df_norm"]
            linestyle = version_line_styles.get(version, "-")

            for joint in joints:
                signal = smooth_series(
                    df[joint],
                    smoothing_window,
                )

                ax.plot(
                    df["t"],
                    signal,
                    label=f"{item['label']} · {joint}",
                    color=joint_color_map.get(joint, None),
                    linestyle=linestyle,
                    alpha=0.88,
                )

        ax.set_xlim(0, max_time)
        ax.set_ylim(-5, 105)

        ax.set_title(
            group_name,
            fontweight="bold",
        )

        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Movement (%)")

        ax.legend(
            fontsize=6.5,
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            frameon=True,
            title="Trial · Joint",
            title_fontsize=7,
        )

    fig.suptitle(
        f"Figure summary — {movement_name} — scale 0–100",
        fontsize=18,
        fontweight="bold",
    )

    if save_figures:
        filename = f"{movement_code}_resum_temps_real_0_100"
        save_figure(fig, movement_folder, filename)

    plt.show()

# ============================================================
# DIFERÈNCIES I MÈTRIQUES V1-V2
# ============================================================

def plot_difference_versions_0_100(versions_data, group_name, joints, movement_folder):
    if 1 not in versions_data or 2 not in versions_data:
        return

    item1 = versions_data[1]
    item2 = versions_data[2]

    movement_name = item1["movement_name"]
    movement_code = item1["movement_code"]

    df1 = item1["df_norm"]
    df2 = item2["df_norm"]

    common_time = np.linspace(
        0,
        min(df1["t"].max(), df2["t"].max()),
        300,
    )

    fig, ax = plt.subplots(
        figsize=(12, 5.8),
        dpi=screen_dpi,
    )

    for joint in joints:
        y1 = np.interp(common_time, df1["t"], df1[joint])
        y2 = np.interp(common_time, df2["t"], df2[joint])

        ax.plot(
            common_time,
            y1 - y2,
            label=joint,
            color=joint_color_map.get(joint, None),
        )

    ax.axhline(
        0,
        linewidth=1.2,
        linestyle="-",
    )

    ax.set_title(
        f"Difference V1 - V2 — {group_name} — {movement_name}",
        pad=14,
        fontweight="bold",
    )

    ax.set_xlabel("Common time (s)")
    ax.set_ylabel("Movement difference (%)")

    ax.legend(
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        frameon=True,
        title="Joint",
    )

    fig.tight_layout()

    if save_figures:
        filename = f"{movement_code}_{nice_filename(group_name)}_diferencia_v1_v2_0_100"
        save_figure(fig, movement_folder, filename)

    plt.show()


def compute_compatibility_metrics_0_100(versions_data):
    if 1 not in versions_data or 2 not in versions_data:
        return None

    item1 = versions_data[1]
    item2 = versions_data[2]

    df1 = item1["df_norm"]
    df2 = item2["df_norm"]

    common_time = np.linspace(
        0,
        min(df1["t"].max(), df2["t"].max()),
        300,
    )

    rows = []

    for joint in all_joints:
        y1 = np.interp(common_time, df1["t"], df1[joint])
        y2 = np.interp(common_time, df2["t"], df2[joint])

        diff = y1 - y2

        mae = np.mean(np.abs(diff))
        rmse = np.sqrt(np.mean(diff ** 2))
        max_abs_error = np.max(np.abs(diff))

        if np.std(y1) == 0 or np.std(y2) == 0:
            corr = np.nan
        else:
            corr = np.corrcoef(y1, y2)[0, 1]

        rows.append({
            "movement_code": item1["movement_code"],
            "movement_name": item1["movement_name"],
            "joint": joint,
            "MAE_percent": mae,
            "RMSE_percent": rmse,
            "max_abs_error_percent": max_abs_error,
            "correlation": corr,
        })

    return pd.DataFrame(rows)


def plot_error_heatmap_0_100(versions_data, movement_folder):
    if 1 not in versions_data or 2 not in versions_data:
        return

    item1 = versions_data[1]
    item2 = versions_data[2]

    movement_name = item1["movement_name"]
    movement_code = item1["movement_code"]

    df1 = item1["df_norm"]
    df2 = item2["df_norm"]

    common_time = np.linspace(
        0,
        min(df1["t"].max(), df2["t"].max()),
        300,
    )

    error_matrix = []

    for joint in all_joints:
        y1 = np.interp(common_time, df1["t"], df1[joint])
        y2 = np.interp(common_time, df2["t"], df2[joint])

        error_matrix.append(
            np.abs(y1 - y2)
        )

    error_matrix = np.array(error_matrix)

    fig, ax = plt.subplots(
        figsize=(13, 8),
        dpi=screen_dpi,
    )

    im = ax.imshow(
        error_matrix,
        aspect="auto",
        origin="lower",
        extent=[common_time.min(), common_time.max(), 0, len(all_joints)],
    )

    ax.set_title(
        f"Absolute error heatmap V1-V2 — {movement_name}",
        pad=14,
        fontweight="bold",
    )

    ax.set_xlabel("Common time (s)")
    ax.set_ylabel("Joint")

    ax.set_yticks(
        np.arange(len(all_joints)) + 0.5,
    )

    ax.set_yticklabels(all_joints)

    cbar = fig.colorbar(
        im,
        ax=ax,
    )

    cbar.set_label("Absolute error (%)")

    fig.tight_layout()

    if save_figures:
        filename = f"{movement_code}_heatmap_error_v1_v2_0_100"
        save_figure(fig, movement_folder, filename)

    plt.show()

# ============================================================
# GENERACIÓ AUTOMÀTICA DE TOTS ELS MOVIMENTS
# ============================================================

all_metrics = []
all_reports = {}

movement_codes = sorted(
    available_files["movement_code"].unique()
)

for movement_code in movement_codes:
    versions_data, reports = load_versions_for_movement(
        available_files,
        movement_code,
    )

    if not versions_data:
        continue

    all_reports[movement_code] = reports

    movement_name = next(iter(versions_data.values()))["movement_name"]
    movement_folder = output_dir / movement_code

    print(f"Processing {movement_code}: {movement_name}")

    for group_name, joints in sensor_groups.items():
        plot_group_versions_0_100(
            versions_data,
            group_name,
            joints,
            movement_folder,
        )

    plot_summary_versions_0_100(
        versions_data,
        sensor_groups,
        movement_folder,
    )

    if 1 in versions_data and 2 in versions_data:
        for group_name, joints in sensor_groups.items():
            plot_difference_versions_0_100(
                versions_data,
                group_name,
                joints,
                movement_folder,
            )

        plot_error_heatmap_0_100(
            versions_data,
            movement_folder,
        )

        metrics_df = compute_compatibility_metrics_0_100(
            versions_data,
        )

        if metrics_df is not None:
            all_metrics.append(metrics_df)

            metrics_df.to_csv(
                movement_folder / f"{movement_code}_metrics_v1_v2_0_100.csv",
                index=False,
            )

if all_metrics:
    all_metrics_df = pd.concat(
        all_metrics,
        ignore_index=True,
    )

    all_metrics_df.to_csv(
        output_dir / "all_movements_metrics_v1_v2_0_100.csv",
        index=False,
    )

    display(
        all_metrics_df.sort_values(
            ["movement_code", "MAE_percent"],
            ascending=[True, False],
        )
    )

print("Procés finalitzat.")

# Informe ràpid de possibles problemes
for movement_code, movement_reports in all_reports.items():
    for label, report in movement_reports.items():
        if (
            report["constant_joints"]
            or report["missing_range_joints"]
            or report["missing_data_joints"]
        ):
            print(f"\nAVÍS {label}:")
            if report["constant_joints"]:
                print("  Joints amb rang zero:", report["constant_joints"])
            if report["missing_range_joints"]:
                print("  Joints sense rang:", report["missing_range_joints"])
            if report["missing_data_joints"]:
                print("  Joints sense dades:", report["missing_data_joints"])

"""## Punt important

Aquest notebook fa dues coses separades:

1. **Lectura del moviment:**  
   Usa els `sensor_names` del YAML de moviment per associar cada valor al seu joint.

2. **Normalització:**  
   Usa el nom del joint per buscar el seu mínim i màxim dins `AA_Anna_Rangs.yaml`.

Per tant, la normalització és robusta encara que l’ordre del fitxer de rangs sigui diferent de l’ordre dels fitxers de moviment.

"""



# ============================================================
# DESCARREGAR RESULTATS DE COLAB EN ZIP
# ============================================================

import shutil
from pathlib import Path

zip_name = "resultats_moviment"

zip_path = shutil.make_archive(
    zip_name,
    "zip",
    output_dir,
)

print("ZIP creat:", zip_path)

try:
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print("No s'ha pogut iniciar la descàrrega automàtica.")
    print("Pots descarregar manualment aquest fitxer:")
    print(zip_path)
    print("Error:", e)