# -*- coding: utf-8 -*-
"""B6_Movements_glove_to_robot_bottleneck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DStFTVRpzX8nDLyuHSsQ8BWZIXwLBZSB

# Movements glove → robot amb bottleneck

Aquest notebook parteix del teu codi base `Movements_glove_to_robot`.

S'ha afegit una **estrangulació intermèdia** (*bottleneck*) a la xarxa neuronal:

```text
dades del guant → capes denses → bottleneck → capes decoder → joints robot
```

La configuració inicial és lleugera:

```python
bottleneck_dim = 8
```

Això permet comprovar si es pot reduir la informació intermèdia del guant mantenint una predicció similar dels 16 joints del robot.


## Afegit en aquesta versió

S'ha incorporat una cel·la de **resum de prediccions per moviment** aplicada al model amb bottleneck. Per cada moviment es genera una figura 2×2 amb:

- trajectòria real del robot;
- prediccions individuals de totes les repeticions del guant;
- mitjana de les prediccions;
- banda de variabilitat ± desviació estàndard.

També s'ha afegit una cel·la final per comprimir i descarregar tots els resultats en un fitxer ZIP des de Google Colab.
"""

import yaml
import re
import pickle
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

np.random.seed(42)
tf.random.set_seed(42)

from pathlib import Path
import zipfile

zip_path = Path("/content/TFM.zip")
base_dir = Path("/content/TFM")

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(base_dir)

glove_movements_dir = base_dir / "Moviments guant"
robot_movements_dir = base_dir / "Moviments Ma Robot"

data_dir = glove_movements_dir
robot_data_dir = robot_movements_dir

glove_ranges_yaml_path = glove_movements_dir / "AA_Rangs1.yaml"

glove_movements_dir = base_dir / "Moviments guant"
robot_movements_dir = base_dir / "Moviments Ma Robot"
glove_static_dir = base_dir / "Estatic Guant"

data_dir = glove_movements_dir
robot_data_dir = robot_movements_dir

glove_ranges_yaml_path = glove_movements_dir / "AA_Rangs1.yaml"

# ============================================================
# CONFIGURACIÓ
# ============================================================

data_dir = glove_movements_dir
robot_data_dir = robot_movements_dir

# Si tens el ZIP amb els moviments del robot, deixa aquest nom.
robot_zip_path = Path("Moviments Ma Robot.zip")

glove_movement_pattern = "A_Mov_*.yaml"
robot_movement_pattern = "AnnaCM_*.yaml"

glove_value_key = "calib_deg"

clip_to_0_100 = True
constant_value_for_nan = 50.0

n_time_points = 1000
time_norm_max = 1000

velocity_threshold_ratio = 0.12
pre_margin_s = 0.10
post_margin_s = 0.10
smoothing_window_detection = 11

manual_segments = {}

use_glove_joints = "all"  # "all" o "robot_common"

test_size = 0.20
random_state = 42

epochs = 150
batch_size = 64
learning_rate = 1e-3

# ============================================================
# CONFIGURACIÓ BOTTLENECK
# ============================================================

use_bottleneck = True
bottleneck_dim = 8  # reducció lleugera inicial. Pots provar 16, 12, 8...
bottleneck_activation = "linear"
bottleneck_l1 = 0.0

output_dir = Path("nn_movements_glove_to_robot_bottleneck")
output_dir.mkdir(exist_ok=True)

show_plots = True

plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "font.size": 11,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linestyle": "--",
})

# ============================================================
# SI HI HA ZIP DEL ROBOT, L'EXTRAIEM AUTOMÀTICAMENT
# ============================================================

if robot_zip_path.exists():
    extract_dir = data_dir
    with zipfile.ZipFile(robot_zip_path, "r") as z:
        z.extractall(extract_dir)
    print(f"ZIP del robot extret: {robot_zip_path}")
else:
    print("No s'ha trobat ZIP del robot. Es buscaran directament els YAML AnnaCM_*.yaml")

movement_names = {
    "PB": "Paper → Botifarra",
    "PO": "Paper → One",
    "PR": "Paper → Rock",
    "PS": "Paper → Scissors",
    "PT": "Paper → Thumb Up",
    "RB": "Rock → Botifarra",
    "RO": "Rock → One",
    "RP": "Rock → Paper",
    "RS": "Rock → Scissors",
    "RT": "Rock → Thumb Up",
}

glove_joint_order = [
    "Thumb j1", "Thumb j2", "Thumb j3", "Thumb j0",
    "Index j1", "Index j2", "Index j3",
    "Middle j1", "Middle j2", "Middle j3",
    "Index j0",
    "Annular j1", "Annular j2", "Annular j3", "Annular j0",
    "Pinky j1", "Pinky j2", "Pinky j3", "Pinky j0",
    "Middle j0",
    "Wrist j1", "Wrist j0",
]

robot_joint_order = [
    "Index j0", "Index j1", "Index j2", "Index j3",
    "Middle j0", "Middle j1", "Middle j2", "Middle j3",
    "Annular j0", "Annular j1", "Annular j2", "Annular j3",
    "Thumb j0", "Thumb j1", "Thumb j2", "Thumb j3",
]

robot_groups = {
    "Index": ["Index j0", "Index j1", "Index j2", "Index j3"],
    "Middle": ["Middle j0", "Middle j1", "Middle j2", "Middle j3"],
    "Annular": ["Annular j0", "Annular j1", "Annular j2", "Annular j3"],
    "Thumb": ["Thumb j0", "Thumb j1", "Thumb j2", "Thumb j3"],
}

robot_joint_limits = {
    "Index j0":   {"min": -0.596932, "max": 0.588071},
    "Index j1":   {"min": -0.284220, "max": 1.798060},
    "Index j2":   {"min": -0.277444, "max": 1.772960},
    "Index j3":   {"min": -0.282001, "max": 1.760870},
    "Middle j0":  {"min": -0.596932, "max": 0.588071},
    "Middle j1":  {"min": -0.284220, "max": 1.798060},
    "Middle j2":  {"min": -0.277444, "max": 1.772960},
    "Middle j3":  {"min": -0.282001, "max": 1.760870},
    "Annular j0": {"min": -0.596932, "max": 0.588071},
    "Annular j1": {"min": -0.284220, "max": 1.798060},
    "Annular j2": {"min": -0.277444, "max": 1.772960},
    "Annular j3": {"min": -0.282001, "max": 1.760870},
    "Thumb j0":   {"min":  0.218668, "max": 1.532940},
    "Thumb j1":   {"min": -0.396993, "max": 1.202960},
    "Thumb j2":   {"min": -0.251244, "max": 1.767010},
    "Thumb j3":   {"min": -0.260209, "max": 1.822620},
}

# ============================================================
# PARSERS DE FITXERS
# ============================================================

def parse_glove_movement_file(path):
    match = re.match(r"A_Mov_([A-Z]{2})(\d+)\.ya?ml$", path.name)
    if not match:
        return None

    movement_code = match.group(1)
    version = int(match.group(2))

    return {
        "movement_code": movement_code,
        "movement_name": movement_names.get(movement_code, movement_code),
        "version": version,
        "label": f"{movement_code}{version}",
        "path": path,
        "file": path.name,
    }


def parse_robot_movement_file(path):
    match = re.match(r"AnnaCM_([A-Z]{2})\.ya?ml$", path.name)
    if not match:
        return None

    movement_code = match.group(1)

    return {
        "movement_code": movement_code,
        "movement_name": movement_names.get(movement_code, movement_code),
        "path": path,
        "file": path.name,
    }


def find_files(data_dir, pattern, parser):
    rows = []
    for path in sorted(data_dir.glob(pattern)):
        parsed = parser(path)
        if parsed is not None:
            rows.append(parsed)

    if not rows:
        raise FileNotFoundError(f"No s'han trobat fitxers amb patró: {pattern}")

    return pd.DataFrame(rows)


glove_files_df = find_files(
    data_dir,
    glove_movement_pattern,
    parse_glove_movement_file,
)

robot_files_df = find_files(
    robot_data_dir,
    robot_movement_pattern,
    parse_robot_movement_file,
)

print("Fitxers guant detectats:")
display(glove_files_df)

print("Fitxers robot detectats:")
display(robot_files_df)

print("Codis guant:", sorted(glove_files_df["movement_code"].unique()))
print("Codis robot:", sorted(robot_files_df["movement_code"].unique()))
print("Moviments del guant sense robot:", sorted(set(glove_files_df["movement_code"]) - set(robot_files_df["movement_code"])))

# ============================================================
# RANGS DEL GUANT
# ============================================================

def load_glove_ranges(path, value_key):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    key_map = {
        "calib_deg": ("calib_min_deg", "calib_max_deg"),
        "raw_deg": ("raw_min_deg", "raw_max_deg"),
        "calib_rad": ("calib_min_rad", "calib_max_rad"),
        "raw_rad": ("raw_min_rad", "raw_max_rad"),
    }

    min_key, max_key = key_map[value_key]

    ranges = {}
    for sensor in data["sensor_range"]["sensors"]:
        ranges[sensor["name"]] = {
            "min": sensor[min_key],
            "max": sensor[max_key],
        }

    missing = [j for j in glove_joint_order if j not in ranges]
    if missing:
        raise ValueError("Falten joints al fitxer de rangs: " + ", ".join(missing))

    return ranges


glove_ranges = load_glove_ranges(glove_ranges_yaml_path, glove_value_key)

# ============================================================
# LECTURA I NORMALITZACIÓ DEL GUANT
# ============================================================

def load_glove_yaml_using_document_order(path, value_key):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    samples = data["recording"]["samples"]
    rows = []

    for sample in samples:
        values = sample[value_key]

        if len(values) != len(glove_joint_order):
            raise ValueError(
                f"{path.name}: té {len(values)} valors, però s'esperaven {len(glove_joint_order)}"
            )

        row = {"t": sample["t"]}

        for i, joint in enumerate(glove_joint_order):
            row[joint] = values[i]

        rows.append(row)

    return pd.DataFrame(rows), data["recording"]


def normalize_glove_0_100(df, ranges, clip=True, constant_value=50.0):
    out = pd.DataFrame()
    out["t"] = df["t"]

    for joint in glove_joint_order:
        q_min = ranges[joint]["min"]
        q_max = ranges[joint]["max"]

        if q_max == q_min:
            out[joint] = constant_value
        else:
            out[joint] = (df[joint] - q_min) / (q_max - q_min) * 100
            if clip:
                out[joint] = out[joint].clip(0, 100)

    return out

# ============================================================
# LECTURA I NORMALITZACIÓ DEL ROBOT
# ============================================================

def extract_robot_samples_from_yaml(data):
    # Aquest format és el dels teus fitxers AnnaCM_*.yaml:
    # una llista directa de vectors de 16 valors.
    if isinstance(data, list):
        return [{"t": i, "values": row} for i, row in enumerate(data)]

    if isinstance(data, dict) and "trajectory" in data:
        samples = data["trajectory"]
        return [
            {
                "t": s.get("t", s.get("time", i)),
                "values": s.get("positions") or s.get("joint_positions") or s.get("values") or s.get("q"),
            }
            for i, s in enumerate(samples)
        ]

    if isinstance(data, dict) and "samples" in data:
        samples = data["samples"]
        return [
            {
                "t": s.get("t", s.get("time", i)),
                "values": s.get("positions") or s.get("joint_positions") or s.get("values") or s.get("q"),
            }
            for i, s in enumerate(samples)
        ]

    if isinstance(data, dict) and "recording" in data and "samples" in data["recording"]:
        samples = data["recording"]["samples"]
        return [
            {
                "t": s.get("t", s.get("time", i)),
                "values": s.get("positions") or s.get("joint_positions") or s.get("values") or s.get("q") or s.get("raw_rad"),
            }
            for i, s in enumerate(samples)
        ]

    if isinstance(data, dict) and "joint_positions" in data:
        return [{"t": i, "values": row} for i, row in enumerate(data["joint_positions"])]

    raise ValueError(
        "No he pogut interpretar l'estructura del YAML del robot. "
        "Adapta la funció extract_robot_samples_from_yaml()."
    )


def load_robot_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    samples = extract_robot_samples_from_yaml(data)
    rows = []

    for sample in samples:
        values = sample["values"]

        if values is None:
            raise ValueError(f"{path.name}: mostra sense valors.")

        if len(values) != len(robot_joint_order):
            raise ValueError(
                f"{path.name}: té {len(values)} valors, però s'esperaven {len(robot_joint_order)}"
            )

        row = {"t": float(sample["t"])}

        for joint, value in zip(robot_joint_order, values):
            row[joint] = float(value)

        rows.append(row)

    return pd.DataFrame(rows)


def normalize_robot_0_100(df, clip=True, constant_value=50.0):
    out = pd.DataFrame()
    out["t"] = df["t"]

    for joint in robot_joint_order:
        q_min = robot_joint_limits[joint]["min"]
        q_max = robot_joint_limits[joint]["max"]

        if q_max == q_min:
            out[joint] = constant_value
        else:
            out[joint] = (df[joint] - q_min) / (q_max - q_min) * 100
            if clip:
                out[joint] = out[joint].clip(0, 100)

    return out

# ============================================================
# SEGMENTACIÓ I NORMALITZACIÓ TEMPORAL
# ============================================================

def smooth_array(x, window=1):
    if window <= 1:
        return x

    return pd.Series(x).rolling(
        window=window,
        center=True,
        min_periods=1,
    ).mean().to_numpy()


def compute_global_velocity(df, joints, smoothing_window=11):
    t = df["t"].to_numpy(dtype=float)
    X = df[joints].to_numpy(dtype=float)

    X = np.nan_to_num(X, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)

    for i in range(X.shape[1]):
        X[:, i] = smooth_array(X[:, i], smoothing_window)

    dX_dt = np.gradient(X, t, axis=0)
    velocity = np.sqrt(np.nanmean(dX_dt ** 2, axis=1))
    velocity = smooth_array(velocity, smoothing_window)

    return velocity


def detect_segment(label, df, joints):
    if label in manual_segments:
        start_t, end_t = manual_segments[label]
        velocity = compute_global_velocity(df, joints, smoothing_window_detection)
        return start_t, end_t, velocity, np.nan, "manual"

    t = df["t"].to_numpy(dtype=float)
    velocity = compute_global_velocity(df, joints, smoothing_window_detection)

    max_v = np.nanmax(velocity)

    if max_v == 0 or np.isnan(max_v):
        return t[0], t[-1], velocity, np.nan, "full_no_velocity"

    threshold = velocity_threshold_ratio * max_v
    active = velocity > threshold

    if not np.any(active):
        return t[0], t[-1], velocity, threshold, "full_no_active"

    idx = np.where(active)[0]
    start_t = max(t[0], t[idx[0]] - pre_margin_s)
    end_t = min(t[-1], t[idx[-1]] + post_margin_s)

    return start_t, end_t, velocity, threshold, "auto"


def crop_and_interpolate(df, joints, start_t=None, end_t=None, n_points=1000, time_norm_max=1000):
    if start_t is None:
        start_t = df["t"].min()
    if end_t is None:
        end_t = df["t"].max()

    seg = df[(df["t"] >= start_t) & (df["t"] <= end_t)].copy()

    if len(seg) < 2:
        raise ValueError("Segment massa curt per interpolar.")

    t = seg["t"].to_numpy(dtype=float)
    t_norm = (t - t.min()) / (t.max() - t.min()) * time_norm_max
    common_t = np.linspace(0, time_norm_max, n_points)

    out = pd.DataFrame({"time_norm": common_t})

    for joint in joints:
        y = seg[joint].to_numpy(dtype=float)
        y = np.nan_to_num(y, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)
        out[joint] = np.interp(common_t, t_norm, y)

    return out, seg

# ============================================================
# PROCESSAMENT DE MOVIMENTS
# ============================================================

if use_glove_joints == "all":
    input_joints = glove_joint_order
elif use_glove_joints == "robot_common":
    input_joints = [j for j in robot_joint_order if j in glove_joint_order]
else:
    raise ValueError("use_glove_joints ha de ser 'all' o 'robot_common'")

processed_glove = {}
processed_robot = {}
segments_rows = []

# Robot
for _, row in robot_files_df.iterrows():
    movement_code = row["movement_code"]

    df_robot_raw = load_robot_yaml(row["path"])
    df_robot_norm = normalize_robot_0_100(
        df_robot_raw,
        clip=clip_to_0_100,
        constant_value=constant_value_for_nan,
    )

    df_robot_aligned, _ = crop_and_interpolate(
        df_robot_norm,
        robot_joint_order,
        start_t=df_robot_norm["t"].min(),
        end_t=df_robot_norm["t"].max(),
        n_points=n_time_points,
        time_norm_max=time_norm_max,
    )

    processed_robot[movement_code] = {
        "movement_code": movement_code,
        "movement_name": row["movement_name"],
        "file": row["file"],
        "df_raw": df_robot_raw,
        "df_norm": df_robot_norm,
        "df_aligned": df_robot_aligned,
    }

# Guant
for _, row in glove_files_df.iterrows():
    label = row["label"]
    movement_code = row["movement_code"]

    if movement_code not in processed_robot:
        print(f"Saltant {label}: no hi ha fitxer robot per moviment {movement_code}")
        continue

    df_raw, recording = load_glove_yaml_using_document_order(row["path"], glove_value_key)
    df_norm = normalize_glove_0_100(
        df_raw,
        glove_ranges,
        clip=clip_to_0_100,
        constant_value=constant_value_for_nan,
    )

    start_t, end_t, velocity, threshold, mode = detect_segment(label, df_norm, input_joints)

    df_aligned, df_segment = crop_and_interpolate(
        df_norm,
        input_joints,
        start_t=start_t,
        end_t=end_t,
        n_points=n_time_points,
        time_norm_max=time_norm_max,
    )

    processed_glove[label] = {
        "label": label,
        "movement_code": movement_code,
        "movement_name": row["movement_name"],
        "version": row["version"],
        "file": row["file"],
        "recording": recording,
        "df_raw": df_raw,
        "df_norm": df_norm,
        "df_segment": df_segment,
        "df_aligned": df_aligned,
        "start_t": start_t,
        "end_t": end_t,
        "velocity": velocity,
        "threshold": threshold,
        "segment_mode": mode,
    }

    segments_rows.append({
        "label": label,
        "movement_code": movement_code,
        "movement_name": row["movement_name"],
        "version": row["version"],
        "file": row["file"],
        "start_t": start_t,
        "end_t": end_t,
        "duration_s": end_t - start_t,
        "segment_mode": mode,
    })

segments_df = pd.DataFrame(segments_rows).sort_values(["movement_code", "version"])
segments_df.to_csv(output_dir / "segments_glove_detected.csv", index=False)

print("Moviments robot:", sorted(processed_robot.keys()))
print("Repeticions guant processades:", len(processed_glove))
display(segments_df)

# ============================================================
# CREACIÓ DEL DATASET
# ============================================================

X_list = []
Y_list = []
meta_rows = []

for label, item in processed_glove.items():
    movement_code = item["movement_code"]

    if movement_code not in processed_robot:
        print(f"Saltant {label}: no hi ha robot per {movement_code}")
        continue

    glove_df = item["df_aligned"]
    robot_df = processed_robot[movement_code]["df_aligned"]

    X_i = glove_df[input_joints].to_numpy(dtype=float)
    Y_i = robot_df[robot_joint_order].to_numpy(dtype=float)

    X_i = np.nan_to_num(X_i, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)
    Y_i = np.nan_to_num(Y_i, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)

    print(
        label,
        "X:", X_i.shape,
        "Y:", Y_i.shape,
        "NaN X:", np.isnan(X_i).sum(),
        "NaN Y:", np.isnan(Y_i).sum(),
    )

    if len(X_i) != len(Y_i):
        raise ValueError(f"{label}: X i Y tenen longitud diferent.")

    X_list.append(X_i)
    Y_list.append(Y_i)

    for i in range(len(X_i)):
        meta_rows.append({
            "label": label,
            "movement_code": movement_code,
            "movement_name": item["movement_name"],
            "version": item["version"],
            "time_norm": glove_df["time_norm"].iloc[i],
            "sample_index": i,
        })

if not X_list:
    raise ValueError(
        "No s'ha creat cap mostra. Revisa que hi hagi coincidència entre codis de guant i robot, "
        "per exemple A_Mov_PB3.yaml i AnnaCM_PB.yaml."
    )

X = np.vstack(X_list)
Y = np.vstack(Y_list)
meta_df = pd.DataFrame(meta_rows)

X = np.nan_to_num(X, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)
Y = np.nan_to_num(Y, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)

if len(X) == 0:
    raise ValueError("El dataset continua buit després del processament.")

print("Dataset de moviments creat")
print("Mostres:", X.shape[0])
print("Inputs:", X.shape[1])
print("Outputs:", Y.shape[1])
print("Moviments:", sorted(meta_df["movement_code"].unique()))
print("Repeticions:", meta_df["label"].nunique())

pd.DataFrame(X, columns=input_joints).head()

# ============================================================
# TRAIN / TEST
# ============================================================

idx = np.arange(len(X))

idx_train, idx_test = train_test_split(
    idx,
    test_size=test_size,
    random_state=random_state,
    stratify=meta_df["movement_code"],
)

X_train, X_test = X[idx_train], X[idx_test]
Y_train, Y_test = Y[idx_train], Y[idx_test]
meta_train = meta_df.iloc[idx_train].reset_index(drop=True)
meta_test = meta_df.iloc[idx_test].reset_index(drop=True)

x_scaler = StandardScaler()
X_train_s = x_scaler.fit_transform(X_train)
X_test_s = x_scaler.transform(X_test)

print("Train:", X_train_s.shape, Y_train.shape)
print("Test:", X_test_s.shape, Y_test.shape)

# ============================================================
# MODEL AMB BOTTLENECK
# ============================================================

from tensorflow.keras import regularizers

def build_model(input_dim, output_dim):
    inputs = keras.Input(
        shape=(input_dim,),
        name="glove_input",
    )

    # Encoder: extrau característiques del guant
    x = layers.Dense(
        256,
        activation="relu",
        name="encoder_dense_256",
    )(inputs)
    x = layers.BatchNormalization(
        name="encoder_bn_256",
    )(x)
    x = layers.Dropout(
        0.10,
        name="encoder_dropout_256",
    )(x)

    x = layers.Dense(
        128,
        activation="relu",
        name="encoder_dense_128",
    )(x)
    x = layers.BatchNormalization(
        name="encoder_bn_128",
    )(x)
    x = layers.Dropout(
        0.10,
        name="encoder_dropout_128",
    )(x)

    x = layers.Dense(
        64,
        activation="relu",
        name="encoder_dense_64",
    )(x)

    # Coll d'ampolla: representació comprimida del guant
    if use_bottleneck:
        bottleneck = layers.Dense(
            bottleneck_dim,
            activation=bottleneck_activation,
            kernel_regularizer=regularizers.l1(bottleneck_l1) if bottleneck_l1 > 0 else None,
            name="bottleneck_layer",
        )(x)
    else:
        bottleneck = x

    # Decoder: transforma la representació comprimida en joints del robot
    x = layers.Dense(
        64,
        activation="relu",
        name="decoder_dense_64",
    )(bottleneck)

    x = layers.Dense(
        32,
        activation="relu",
        name="decoder_dense_32",
    )(x)

    outputs = layers.Dense(
        output_dim,
        activation="linear",
        name="robot_output",
    )(x)

    model = keras.Model(
        inputs=inputs,
        outputs=outputs,
        name="glove_to_robot_bottleneck_model",
    )

    model.compile(
        optimizer=keras.optimizers.Adam(
            learning_rate=learning_rate,
        ),
        loss="mse",
        metrics=["mae"],
    )

    return model


model = build_model(
    X_train_s.shape[1],
    Y_train.shape[1],
)

model.summary()

print("Input dim:", X_train_s.shape[1])
print("Bottleneck dim:", bottleneck_dim if use_bottleneck else "sense bottleneck")
print("Output dim:", Y_train.shape[1])

# ============================================================
# ENTRENAMENT
# ============================================================

callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=20,
        restore_best_weights=True,
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=8,
        min_lr=1e-5,
    ),
]

history = model.fit(
    X_train_s,
    Y_train,
    validation_split=0.20,
    epochs=epochs,
    batch_size=batch_size,
    callbacks=callbacks,
    verbose=1,
)

# ============================================================
# TRAINING LOSS
# ============================================================

fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(history.history["loss"], label="train loss")
ax.plot(history.history["val_loss"], label="validation loss")
ax.set_title("Training loss")
ax.set_xlabel("Epoch")
ax.set_ylabel("MSE")
ax.legend()
fig.tight_layout()
fig.savefig(output_dir / "training_loss.png", bbox_inches="tight")
plt.show()

# ============================================================
# AVALUACIÓ
# ============================================================

Y_pred = model.predict(X_test_s)

mae_global = mean_absolute_error(Y_test, Y_pred)
rmse_global = np.sqrt(mean_squared_error(Y_test, Y_pred))

print(f"MAE global:  {mae_global:.3f} punts sobre 0–100")
print(f"RMSE global: {rmse_global:.3f} punts sobre 0–100")

metrics_rows = []

for j, joint in enumerate(robot_joint_order):
    y_true = Y_test[:, j]
    y_pred = Y_pred[:, j]

    metrics_rows.append({
        "joint": joint,
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "R2": r2_score(y_true, y_pred) if np.std(y_true) > 0 else np.nan,
    })

metrics_df = pd.DataFrame(metrics_rows)
metrics_df.to_csv(output_dir / "metrics_by_robot_joint.csv", index=False)
metrics_df.sort_values("MAE", ascending=False)

# ============================================================
# REPRESENTACIÓ COMPRIMIDA DEL BOTTLENECK
# ============================================================

if use_bottleneck:
    bottleneck_model = keras.Model(
        inputs=model.input,
        outputs=model.get_layer("bottleneck_layer").output,
    )

    Z_train = bottleneck_model.predict(
        X_train_s,
        verbose=0,
    )

    Z_test = bottleneck_model.predict(
        X_test_s,
        verbose=0,
    )

    print("Bottleneck train:", Z_train.shape)
    print("Bottleneck test:", Z_test.shape)

    bottleneck_columns = [
        f"bottleneck_{i+1}"
        for i in range(Z_test.shape[1])
    ]

    bottleneck_df = meta_test.copy()

    for i, col in enumerate(bottleneck_columns):
        bottleneck_df[col] = Z_test[:, i]

    bottleneck_df.to_csv(
        output_dir / "bottleneck_representation_test.csv",
        index=False,
    )

    display(
        bottleneck_df.head()
    )
else:
    print("El model no utilitza bottleneck.")

# ============================================================
# MÈTRIQUES PER MOVIMENT
# ============================================================

pred_df = meta_test.copy()

for j, joint in enumerate(robot_joint_order):
    pred_df[f"true_{joint}"] = Y_test[:, j]
    pred_df[f"pred_{joint}"] = Y_pred[:, j]
    pred_df[f"error_{joint}"] = Y_pred[:, j] - Y_test[:, j]

movement_rows = []

for movement_code, group in pred_df.groupby("movement_code"):
    for joint in robot_joint_order:
        y_true = group[f"true_{joint}"].to_numpy()
        y_pred = group[f"pred_{joint}"].to_numpy()

        movement_rows.append({
            "movement_code": movement_code,
            "movement_name": movement_names.get(movement_code, movement_code),
            "joint": joint,
            "MAE": mean_absolute_error(y_true, y_pred),
            "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
            "true_mean": y_true.mean(),
            "pred_mean": y_pred.mean(),
            "pred_std": y_pred.std(),
        })

movement_metrics_df = pd.DataFrame(movement_rows)
movement_metrics_df.to_csv(output_dir / "metrics_by_movement_and_joint.csv", index=False)

movement_metrics_df.sort_values(["movement_code", "MAE"], ascending=[True, False]).head(30)

# ============================================================
# PLOTS DE TRAJECTÒRIES
# ============================================================

def safe_name(text):
    return (
        text.replace(" ", "_")
        .replace("→", "to")
        .replace("í", "i")
        .replace("à", "a")
        .replace("è", "e")
        .replace("é", "e")
        .replace("ó", "o")
        .replace("ú", "u")
        .replace("/", "_")
    )


def predict_full_glove_repetition(item):
    X_full = item["df_aligned"][input_joints].to_numpy(dtype=float)
    X_full = np.nan_to_num(X_full, nan=constant_value_for_nan, posinf=100.0, neginf=0.0)
    X_full_s = x_scaler.transform(X_full)
    Y_full_pred = model.predict(X_full_s, verbose=0)

    pred = pd.DataFrame(Y_full_pred, columns=robot_joint_order)
    pred["time_norm"] = item["df_aligned"]["time_norm"].to_numpy()

    return pred


for label, item in processed_glove.items():
    movement_code = item["movement_code"]
    movement_name = item["movement_name"]
    movement_folder = output_dir / movement_code / label
    movement_folder.mkdir(parents=True, exist_ok=True)

    pred_full_df = predict_full_glove_repetition(item)
    robot_df = processed_robot[movement_code]["df_aligned"]

    for group_name, joints in robot_groups.items():
        fig, ax = plt.subplots(figsize=(12, 5.8))

        for joint in joints:
            ax.plot(
                robot_df["time_norm"],
                robot_df[joint],
                linestyle="--",
                label=f"Real robot · {joint}",
            )

            ax.plot(
                pred_full_df["time_norm"],
                pred_full_df[joint],
                label=f"Pred NN · {joint}",
            )

        ax.set_title(f"{label} — {movement_name} — {group_name}")
        ax.set_xlabel(f"Normalized time 0–{time_norm_max}")
        ax.set_ylabel("Joint robot (%)")
        ax.set_xlim(0, time_norm_max)
        ax.set_ylim(-5, 105)
        ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=True)

        fig.tight_layout()
        fig.savefig(
            movement_folder / f"{label}_{safe_name(group_name)}_trajectory_pred_vs_real.png",
            bbox_inches="tight",
        )

        if show_plots:
            plt.show()
        else:
            plt.close(fig)

# ============================================================
# RESUM DE PREDICCIONS PER MOVIMENT
# ============================================================

def build_predictions_by_movement():
    """Calcula les prediccions de totes les repeticions i les agrupa per moviment."""

    predictions_by_movement = {}

    for label, item in processed_glove.items():
        movement_code = item["movement_code"]
        movement_name = item["movement_name"]

        pred_full_df = predict_full_glove_repetition(item)

        if movement_code not in predictions_by_movement:
            predictions_by_movement[movement_code] = {
                "movement_code": movement_code,
                "movement_name": movement_name,
                "predictions": {},
                "robot_df": processed_robot[movement_code]["df_aligned"],
            }

        predictions_by_movement[movement_code]["predictions"][label] = pred_full_df

    return predictions_by_movement


def compute_prediction_summary_for_movement(prediction_items):
    """Calcula mitjana, desviació, mínim i màxim entre repeticions per cada joint."""

    labels = sorted(prediction_items.keys())
    reference_time = prediction_items[labels[0]]["time_norm"].to_numpy()

    summary = pd.DataFrame({
        "time_norm": reference_time,
    })

    for joint in robot_joint_order:
        stacked = []

        for label in labels:
            df = prediction_items[label]

            y = np.interp(
                reference_time,
                df["time_norm"].to_numpy(),
                df[joint].to_numpy(),
            )

            stacked.append(y)

        stacked = np.vstack(stacked)

        summary[f"{joint}_mean"] = stacked.mean(axis=0)
        summary[f"{joint}_std"] = stacked.std(axis=0)
        summary[f"{joint}_min"] = stacked.min(axis=0)
        summary[f"{joint}_max"] = stacked.max(axis=0)

    return summary


def plot_movement_prediction_summary_2x2(movement_code, movement_data):
    """Figura resum 2x2 per moviment: robot real + prediccions individuals + mitjana ± std."""

    movement_name = movement_data["movement_name"]
    prediction_items = movement_data["predictions"]
    robot_df = movement_data["robot_df"]

    if not prediction_items:
        return

    movement_folder = output_dir / movement_code / "summary_predictions"
    movement_folder.mkdir(parents=True, exist_ok=True)

    summary_df = compute_prediction_summary_for_movement(
        prediction_items,
    )

    summary_df.to_csv(
        movement_folder / f"{movement_code}_summary_prediction_mean_std.csv",
        index=False,
    )

    fig, axes = plt.subplots(
        2,
        2,
        figsize=(24, 12),
        dpi=150,
        sharex=True,
        constrained_layout=True,
    )

    axes = axes.flatten()

    for ax, (group_name, joints) in zip(axes, robot_groups.items()):
        for joint in joints:
            # Trajectòria real del robot
            ax.plot(
                robot_df["time_norm"],
                robot_df[joint],
                linestyle="--",
                linewidth=1.8,
                label=f"Real robot · {joint}",
            )

            # Prediccions individuals de cada repetició del guant
            for label, pred_df in sorted(prediction_items.items()):
                ax.plot(
                    pred_df["time_norm"],
                    pred_df[joint],
                    linewidth=1.0,
                    alpha=0.25,
                    label="_nolegend_",
                )

            mean_col = f"{joint}_mean"
            std_col = f"{joint}_std"

            # Mitjana de les prediccions
            ax.plot(
                summary_df["time_norm"],
                summary_df[mean_col],
                linewidth=2.2,
                label=f"Mean pred · {joint}",
            )

            # Banda de variabilitat entre repeticions
            ax.fill_between(
                summary_df["time_norm"],
                summary_df[mean_col] - summary_df[std_col],
                summary_df[mean_col] + summary_df[std_col],
                alpha=0.15,
            )

        ax.set_title(
            group_name,
            fontweight="bold",
        )
        ax.set_ylabel("Joint robot (%)")
        ax.set_xlim(0, time_norm_max)
        ax.set_ylim(-5, 105)

        ax.legend(
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            frameon=True,
            fontsize=7,
            title="Trajectory",
            title_fontsize=8,
        )

    for ax in axes[-2:]:
        ax.set_xlabel(f"Normalized time 0–{time_norm_max}")

    fig.suptitle(
        f"Predictions with bottleneck summary — {movement_code} — {movement_name}",
        fontsize=18,
        fontweight="bold",
    )

    fig.savefig(
        movement_folder / f"{movement_code}_summary_predictions_2x2_bottleneck.png",
        bbox_inches="tight",
    )

    fig.savefig(
        movement_folder / f"{movement_code}_summary_predictions_2x2_bottleneck.pdf",
        bbox_inches="tight",
    )

    if show_plots:
        plt.show()
    else:
        plt.close(fig)


# ============================================================
# GENERAR TOTS ELS RESUMS
# ============================================================

predictions_by_movement = build_predictions_by_movement()

for movement_code, movement_data in sorted(predictions_by_movement.items()):
    print(
        f"Generant resum de prediccions amb bottleneck: {movement_code} — {movement_data['movement_name']}"
    )

    plot_movement_prediction_summary_2x2(
        movement_code,
        movement_data,
    )

print("Resums de prediccions amb bottleneck generats.")

# ============================================================
# ERROR PER JOINT
# ============================================================

plot_df = metrics_df.copy()
plot_df["joint"] = pd.Categorical(plot_df["joint"], categories=robot_joint_order, ordered=True)
plot_df = plot_df.sort_values("joint")

fig, ax = plt.subplots(figsize=(12, 6))
ax.bar(plot_df["joint"].astype(str), plot_df["MAE"])
ax.set_title("MAE for robot joint — movements")
ax.set_xlabel("Joint robot")
ax.set_ylabel("MAE in scale 0–100")
ax.tick_params(axis="x", rotation=45)
fig.tight_layout()
fig.savefig(output_dir / "mae_by_robot_joint.png", bbox_inches="tight")
plt.show()

# ============================================================
# GUARDAR MODEL
# ============================================================

model.save(output_dir / "glove_to_robot_movements_bottleneck.keras")

with open(output_dir / "x_scaler.pkl", "wb") as f:
    pickle.dump(x_scaler, f)

config = {
    "input_joints": input_joints,
    "robot_joint_order": robot_joint_order,
    "glove_value_key": glove_value_key,
    "clip_to_0_100": clip_to_0_100,
    "constant_value_for_nan": constant_value_for_nan,
    "n_time_points": n_time_points,
    "time_norm_max": time_norm_max,
    "use_bottleneck": use_bottleneck,
    "bottleneck_dim": bottleneck_dim,
    "bottleneck_activation": bottleneck_activation,
    "bottleneck_l1": bottleneck_l1,
}

with open(output_dir / "model_config.pkl", "wb") as f:
    pickle.dump(config, f)

print("Model guardat a:", output_dir)

"""## Millores incorporades

- Els fitxers del robot `AnnaCM_*.yaml` en format llista directa de vectors ja es llegeixen correctament.
- Si un joint té rang zero, es normalitza a valor neutre `50`.
- Qualsevol `NaN`, `+inf` o `-inf` residual es substitueix abans de crear el dataset.
- El codi mostra per pantalla quins fitxers ha detectat i quins codis de moviment coincideixen entre guant i robot.

## Com provar diferents graus d'estrangulació

Aquest notebook comença amb:

```python
bottleneck_dim = 18
```

Això és una reducció lleugera. Per anar estrenyent:

```python
bottleneck_dim = 16
bottleneck_dim = 12
bottleneck_dim = 8
```

Compara sempre:

- `MAE global`
- `RMSE global`
- plots de trajectòria robot real vs predicció
- `bottleneck_representation_test.csv`

Si el MAE es manté semblant, vol dir que la informació del guant es pot comprimir sense perdre gaire rendiment.
"""

# ============================================================
# DESCARREGAR RESULTATS DE COLAB EN ZIP
# ============================================================

import shutil
from pathlib import Path

zip_name = "resultats_bottleneck_moviments"

# Crea un ZIP amb tot el contingut de output_dir
zip_path = shutil.make_archive(
    zip_name,
    "zip",
    output_dir,
)

print("ZIP creat:", zip_path)

# Descàrrega directa en Google Colab
try:
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print("No s'ha pogut iniciar la descàrrega automàtica.")
    print("Pots descarregar manualment aquest fitxer:")
    print(zip_path)
    print("Error:", e)